In [2]:
import sqlite3

In [4]:
import pandas as pd
import numpy as np

path1 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\borse.csv'
path2 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdsll.csv'
path3 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdslpts.csv'
path4 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdsul.csv'
path5 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdsupts.csv'
path6 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\commercial.csv'
path7 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\ReviewTriggerLevels.csv'
path8 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\signalnarrativewithinsert.csv'
path9 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\HighRiskCodes.csv'
path10 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\BSv2.csv'
path11 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\actions.csv'
path12 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\NBA_scorecard.csv'
path13 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\OpenBanking.csv'
path14 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\PnLv2.csv'
#path15 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\BSv2.csv'
path16 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\PnLv2_T.csv'
path17 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\BSv2_T.csv'
path18 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\invoicev2.csv'

borse_df = pd.read_csv(path1)
thresholdsll_df = pd.read_csv(path2)
thresholdslpts_df = pd.read_csv(path3)
thresholdsul_df = pd.read_csv(path4)
thresholdsupts_df = pd.read_csv(path5)
commercial_df = pd.read_csv(path6,  parse_dates=["date of incorporation"])
review_trigger_levels_df = pd.read_csv(path7)
signal_narrative_df = pd.read_csv(path8)
high_risk_codes_df = pd.read_csv(path9)
BS_df = pd.read_csv(path10)
actions_df = pd.read_csv(path11)
NBA_scorecard_df = pd.read_csv(path12)
OpenBanking_df = pd.read_csv(path13, parse_dates=["open date"])
PnL_df = pd.read_csv(path14)
PnL_T_df = pd.read_csv(path16)
BS_T_df = pd.read_csv(path17)
invoice_df = pd.read_csv(path18)

print(borse_df)
#print(thresholdsll_df)
#print(thresholdslpts_df)
#print(thresholdsul_df)
#print(thresholdsupts_df)
#print(commercial_df)
#print(review_trigger_levels_df)
#print(signal_narrative_df)
#print(high_risk_codes_df)
#print(BS_df)
#print(actions_df)
#print(NBA_scorecard_df)
#print(OpenBanking_df)
#print(PnL_T_df)
#print(BS_T_df)

   id  share price
0   1           23

In [6]:
conn = sqlite3.connect('TestDB9.db') 
c = conn.cursor()
borse_df.to_sql('borse', conn, if_exists='replace', index = False)
thresholdsll_df.to_sql('thresholdsll', conn, if_exists='replace', index = False)
thresholdslpts_df.to_sql('thresholdslpts', conn, if_exists='replace', index = False)
thresholdsul_df.to_sql('thresholdsul', conn, if_exists='replace', index = False)
thresholdsupts_df.to_sql('thresholdsupts', conn, if_exists='replace', index = False)
commercial_df.to_sql('commercial', conn, if_exists='replace', index = False)
review_trigger_levels_df.to_sql('review_trigger_levels', conn, if_exists='replace', index = False)
signal_narrative_df.to_sql('signal_narrative', conn, if_exists='replace', index = False)
high_risk_codes_df.to_sql('high_risk_codes', conn, if_exists='replace', index = False)
BS_df.to_sql('BS', conn, if_exists='replace', index = False)
actions_df.to_sql('actions', conn, if_exists='replace', index = False)
NBA_scorecard_df.to_sql('NBA_scorecard', conn, if_exists='replace', index = False)
OpenBanking_df.to_sql('OpenBanking', conn, if_exists='replace', index = False)
PnL_df.to_sql('PnL', conn, if_exists='replace', index = False)
BS_T_df.to_sql('BS_T', conn, if_exists='replace', index = False)
PnL_T_df.to_sql('PnL_T', conn, if_exists='replace', index = False)
invoice_df.to_sql('invoice', conn, if_exists='replace', index = False)

In [7]:
c.execute('''  
SELECT * FROM PnL_T
          ''')

In [9]:
import pandas as pd

c = conn.cursor()
q = """
SELECT *
FROM PnL_T
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
PnL_T_df = pd.DataFrame(c.fetchall(), columns=cols)
PnL_T_df.head()

print(cols)

['Party_id', 'Month', 'Sales', 'Direct Cost of Sales', 'Production Payroll', 'Other', 'Total Cost of Sales', 'Gross Margin', 'Gross Margin %', 'Operating Expenses:', 'Sales and Marketing Expenses', 'Sales and Marketing Payroll', 'Rent', 'Travel', 'Burglar Alarm', 'Total Sales & Marketing Expenses', 'Sales and Marketing %', 'General and Administrative Expenses', 'General & Administrative Payroll', 'Payroll Expense', 'Payroll Burden', 'Depreciation', 'Office Supplies', 'Utilities', 'Insurance', 'Telephone', 'Total General & Administrative Expenses', 'General and Administrative %', 'Other Expenses', 'Other Payroll', 'Advertising', 'Loan Repayment', 'Inventory', 'Accounting/legal', 'Total Other Expenses', 'Other %', 'Total Operating Expenses', 'Profit Before Interest and Taxes', 'Interest Expense Short-term', 'Interest Expense Long-term', 'Taxes Incurred', 'Extraordinary Items', 'Net Profit', 'Net Profit/Sales']

In [30]:
c.close()

In [31]:
conn.commit()
c.close()

In [32]:
c = conn.cursor()
q = """
SELECT *
FROM thresholdslpts
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
df = pd.DataFrame(c.fetchall(), columns=cols)
df.head()

,lower breach,Conduct,Liquidity,Credit,Capital,Contagion,Trade,AML,Fraud
0,DirectorDisqualified,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
1,DirectorCCJ,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
2,DirectorBankcrupcy,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
3,CreditScoreAndNoSecurity,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
4,ValueLoanOutstandingLtvRatio,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN

In [10]:
c = conn.cursor()
q = """
SELECT *
FROM BS_T
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
BS_T_df = pd.DataFrame(c.fetchall(), columns=cols)
BS_T_df.head()

print(cols)

#print(BS_T_df)

['Party_id', 'Month', 'Assets', 'Short-term Assets', 'Cash', 'Accounts Receivable', 'Inventory', 'Other Short-term Assets', 'Total Short-term Assets', 'Long-term Assets', 'Capital Assets', 'Accumulated Depreciation', 'Total Long-term Assets', 'Total Assets', 'Liabilities and Capital', 'Accounts Payable', 'Short-term Notes', 'Other Short-term Liabilities', 'Subtotal Short-term Liabilities', 'Long-term Liabilities', 'Total Liabilities', 'Paid in Capital', 'Dividends paid', 'Retained Earnings', 'Earnings', 'Total Capital', 'Total Liabilities and Capital', 'Net Worth']

In [34]:
c = conn.cursor()
q = """
SELECT *
FROM borse
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
borse_df = pd.DataFrame(c.fetchall(), columns=cols)
borse_df.head()

   id  share price
0   1           23

In [35]:
c = conn.cursor()
q = """
SELECT *
FROM commercial
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
commercial_df = pd.DataFrame(c.fetchall(), columns=cols)
commercial_df.head()


print(commercial_df)

   party_id  disqualified director  bankcrupt director  CCJ director  \
0         0                      1                   1             1
1         1                      0                   0             0

   changed director  credit score  new business director  \
0                 1           650                      1
1                 0           460                      0

   regional economy index date of incorporation postcode
0                       8   2010-01-01 00:00:00      EH5
1                       6   2019-03-05 00:00:00      EC4

In [11]:
c = conn.cursor()
q = """
SELECT *
FROM invoice
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
invoice_df = pd.DataFrame(c.fetchall(), columns=cols)
invoice_df.head()

print(cols)

['Id', 'PartyId', 'CustomerId', 'SequenceNumber', 'InvoiceReference', 'DueDate', 'CreatedDate', 'RaisedDate', 'ReceivedValue', 'IsInsured', 'CurrencyCode', 'CurrencyRate', 'ModifiedDate', 'PaidDate', 'NetValue', 'DiscountValue', 'DiscountPercent', 'GrossValue', 'TaxValue', 'OutstandingAmountValue', 'ValidDate', 'Status', 'DaysToPay', 'Customer credit score']

In [37]:
c = conn.cursor()
q = """
SELECT *
FROM high_risk_codes
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
high_risk_codes_df = pd.DataFrame(c.fetchall(), columns=cols)
high_risk_codes_df.head()

   high risk sic code
0                  23
1                  45
2                 654

In [38]:
import numpy as np
import pandas as pd

months = []
for i in range(36) : months.append(i)
    
BS_line_items= pd.Series(BS_T_df.columns)
PnL_line_items= pd.Series(PnL_T_df.columns)

#print(BS_line_items)
print(PnL_line_items)

0                                    Party_id
1                                       Month
2                                       Sales
3                        Direct Cost of Sales
4                          Production Payroll
5                                       Other
6                         Total Cost of Sales
7                                Gross Margin
8                              Gross Margin %
9                         Operating Expenses:
10               Sales and Marketing Expenses
11                Sales and Marketing Payroll
12                                       Rent
13                                     Travel
14                              Burglar Alarm
15           Total Sales & Marketing Expenses
16                      Sales and Marketing %
17        General and Administrative Expenses
18           General & Administrative Payroll
19                            Payroll Expense
20                             Payroll Burden
21                               Depreciation
22                            Office Supplies
23                                  Utilities
24                                  Insurance
25                                  Telephone
26    Total General & Administrative Expenses
27               General and Administrative %
28                             Other Expenses
29                              Other Payroll
30                                Advertising
31                             Loan Repayment
32                                  Inventory
33                           Accounting/legal
34                       Total Other Expenses
35                                    Other %
36                   Total Operating Expenses
37           Profit Before Interest and Taxes
38                Interest Expense Short-term
39                 Interest Expense Long-term
40                             Taxes Incurred
41                        Extraordinary Items
42                                 Net Profit
43                           Net Profit/Sales
dtype: object

In [39]:
c = conn.cursor()
q = """
SELECT distinct(Party_id)
FROM BS_T
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
companies_df = pd.DataFrame(c.fetchall(), columns=cols)
companies_df.head()

companies_s = pd.Series(companies_df["Party_id"])

for company in companies_s : print(company)

1
2

In [40]:
c = conn.cursor()
q = """
SELECT *
FROM borse
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
borse_df = pd.DataFrame(c.fetchall(), columns=cols)
borse_df.head()

   id  share price
0   1           23

In [41]:

for n, company in enumerate(companies_s) :
    if n == 0 : 
        BS = BS_T_df.loc[BS_T_df['Party_id'] == company].T.to_numpy()
        PnL = PnL_T_df.loc[PnL_T_df['Party_id'] == company].T.to_numpy()
    else :     
        BS_next = BS_T_df.loc[BS_T_df['Party_id'] == company].T.to_numpy()
        BS = np.stack((BS, BS_next), axis= 2)
        PnL_next = PnL_T_df.loc[PnL_T_df['Party_id'] == company].T.to_numpy()
        PnL = np.stack((PnL, PnL_next), axis= 2)
        
#print(BS)
#print(PnL)

In [42]:
#np.shape(BS)
#print(BS[:,0,1])
months = BS[1, :, 1]
print(months)

['17-Dec' '18-Jan' '18-Feb' '18-Mar' '18-Apr' '18-May' '18-Jun' '18-Jul'
 '18-Aug' '18-Sep' '18-Oct' '18-Nov' '18-Dec' '19-Jan' '19-Feb' '19-Mar'
 '19-Apr' '19-May' '19-Jun' '19-Jul' '19-Aug' '19-Sep' '19-Oct' '19-Nov'
 '19-Dec' '20-Jan' '20-Feb' '20-Mar' '20-Apr' '20-May' '20-Jun' '20-Jul'
 '20-Aug' '20-Sep' '20-Oct' '20-Nov']

In [43]:
PnL_key_line_items = [
"Sales",
"Total Cost of Sales",
"Gross Margin",
"Total Sales & Marketing Expenses",
"Rent",
"Payroll Expense",
"Total General & Administrative Expenses",
"Loan Repayment",
"Inventory",
"Depreciation",
"Total Operating Expenses",
"Profit Before Interest and Taxes",
"Interest Expense Short-term",
"Interest Expense Long-term",
"Taxes Incurred",
"Extraordinary Items",
"Net Profit",
]


BS_key_line_items = [
"Accounts Receivable",
"Inventory",
"Other Short-term Assets",
"Total Short-term Assets",    
"Long-term Assets",
"Total Assets",
"Cash",
"Accounts Payable",
"Short-term Notes",
"Other Short-term Liabilities",
"Subtotal Short-term Liabilities",    
"Long-term Liabilities",
"Total Liabilities",
"Paid in Capital",
"Dividends paid",
"Retained Earnings",    
"Earnings",    
"Total Capital",   
"Net Worth"    
]



PnL_st = set(PnL_key_line_items)
PnL_line_indices =  {e:i for i, e in enumerate(PnL_line_items) if e in PnL_st}

BS_st = set(BS_key_line_items)
BS_line_indices = {e:i for i, e in enumerate(BS_line_items) if e in BS_st}

print(PnL_line_indices)
print(BS_line_indices)

{'Sales': 2, 'Total Cost of Sales': 6, 'Gross Margin': 7, 'Rent': 12, 'Total Sales & Marketing Expenses': 15, 'Payroll Expense': 19, 'Depreciation': 21, 'Total General & Administrative Expenses': 26, 'Loan Repayment': 31, 'Inventory': 32, 'Total Operating Expenses': 36, 'Profit Before Interest and Taxes': 37, 'Interest Expense Short-term': 38, 'Interest Expense Long-term': 39, 'Taxes Incurred': 40, 'Extraordinary Items': 41, 'Net Profit': 42}
{'Cash': 4, 'Accounts Receivable': 5, 'Inventory': 6, 'Other Short-term Assets': 7, 'Total Short-term Assets': 8, 'Long-term Assets': 9, 'Total Assets': 13, 'Accounts Payable': 15, 'Short-term Notes': 16, 'Other Short-term Liabilities': 17, 'Subtotal Short-term Liabilities': 18, 'Long-term Liabilities': 19, 'Total Liabilities': 20, 'Paid in Capital': 21, 'Dividends paid': 22, 'Retained Earnings': 23, 'Earnings': 24, 'Total Capital': 25, 'Net Worth': 27}

In [44]:
print(BS_line_items)

0                            Party_id
1                               Month
2                              Assets
3                   Short-term Assets
4                                Cash
5                 Accounts Receivable
6                           Inventory
7             Other Short-term Assets
8             Total Short-term Assets
9                    Long-term Assets
10                     Capital Assets
11           Accumulated Depreciation
12             Total Long-term Assets
13                       Total Assets
14            Liabilities and Capital
15                   Accounts Payable
16                   Short-term Notes
17       Other Short-term Liabilities
18    Subtotal Short-term Liabilities
19              Long-term Liabilities
20                  Total Liabilities
21                    Paid in Capital
22                     Dividends paid
23                  Retained Earnings
24                           Earnings
25                      Total Capital
26      Total Liabilities and Capital
27                          Net Worth
dtype: object

In [45]:
PnL.shape

(44, 36, 2)

In [46]:
PnL_key_lines = PnL[list(PnL_line_indices.values()), :, :]
BS_key_lines = BS[list(BS_line_indices.values()), :, :]
#PnL_key_lines.shape
#print(BS_key_lines)
#print(PnL_key_lines)

In [47]:
#print(BS_line_indices["Total Short-term Assets"])
#print(TotalCurrentAssetsValue)

TotalCurrentAssetsValue = BS[BS_line_indices["Total Short-term Assets"], :, :]

print(TotalCurrentAssetsValue)

[[53272.46377 53272.46377]
 [40861.1117 40861.1117]
 [39972.7196 39972.7196]
 [34328.31045 34328.31045]
 [30745.495160000002 30745.495160000002]
 [26641.54423 26641.54423]
 [17605.50488 17605.50488]
 [11481.95935 11481.95935]
 [6744.490490000001 6744.490490000001]
 [3987.857693 3987.857693]
 [-3286.6657649999997 -3286.6657649999997]
 [3069.67825 3069.67825]
 [9922.869469 9922.869469]
 [-2611.096582 -2611.096582]
 [-3693.0808869999996 -3693.0808869999996]
 [-10229.66697 -10229.66697]
 [-13498.974069999998 -13498.974069999998]
 [-19131.066730000002 -19131.066730000002]
 [-27296.02863 -27296.02863]
 [-35000.69152 -35000.69152]
 [-38851.03584 -38851.03584]
 [-43527.1789 -43527.1789]
 [-49414.26613 -49414.26613]
 [-146211.9271 -146211.9271]
 [-137648.2855 -137648.2855]
 [-151341.279 -151341.279]
 [-153739.8848 -153739.8848]
 [-161158.235 -161158.235]
 [-165843.3544 -165843.3544]
 [-171852.277 -171852.277]
 [-181284.1239 -181284.1239]
 [-188792.5867 -188792.5867]
 [-194602.6417 -194602.6417]
 [-199348.3864 -199348.3864]
 [-207283.9744 -207283.9744]
 [-204482.3621 -204482.3621]]

In [52]:
SalesValue = PnL[PnL_line_indices["Sales"], :, :]
DirectCostofSalesValue = PnL[PnL_line_indices["Total Cost of Sales"], :, :]
TotalCurrentAssetsValue = BS[BS_line_indices["Total Short-term Assets"], :, :]
TotalCurrentLiabilitiesValue = BS[BS_line_indices["Subtotal Short-term Liabilities"], :, :]
TotalEquityValue = BS[BS_line_indices["Total Capital"], :, :]
LongTermLiabilitiesValue =  BS[BS_line_indices["Long-term Liabilities"], :, :]
OperatingExpensesValue =  PnL[PnL_line_indices["Total Operating Expenses"], :, :]
TotalNetAssetsValue =  BS[BS_line_indices["Total Assets"], :, :] - BS[BS_line_indices["Total Liabilities"], :, :]
TotalFixedAssetValue =  BS[BS_line_indices["Long-term Assets"], :, :]
TotalIncomeValue = PnL[PnL_line_indices["Sales"], :, :]
OtherIncomeValue =  np.zeros(np.shape(TotalIncomeValue))
OwnersFundsValue =  BS[BS_line_indices["Total Capital"], :, :]
#SalesValue = PnL_key_lines[PnL_key_line_items.index("Sales"), :, :]
DepreciationValue =  PnL[PnL_line_indices["Depreciation"], :, :]
OperatingCostsValue =  PnL[PnL_line_indices["Total Operating Expenses"], :, :]
PBITValue = PnL[PnL_line_indices["Profit Before Interest and Taxes"], :, :]
InterestValue = PnL[PnL_line_indices["Interest Expense Short-term"], :, :] + PnL[PnL_line_indices["Interest Expense Long-term"], :, :]
TaxValue = PnL[PnL_line_indices["Taxes Incurred"], :, :]
PATValue = PnL[PnL_line_indices["Net Profit"], :, :]
PaidInCapitalValue = BS[BS_line_indices["Paid in Capital"], :, :]
DividendValue = BS[BS_line_indices["Dividends paid"], :, :]
RetainedEarningsValue = BS[BS_line_indices["Retained Earnings"], :, :]
EarningsValue = BS[BS_line_indices["Earnings"], :, :]
OrdinaryShareNumber =  np.zeros(np.shape(TotalIncomeValue)) 
OrdinarySharePriceValue =  np.zeros(np.shape(TotalIncomeValue)) 
InventoryValue = BS[BS_line_indices["Inventory"], :, :]
DebtValue = BS[BS_line_indices["Short-term Notes"], :, :]
CashValue = BS[BS_line_indices["Cash"], :, :]
NetWorthValue = BS[BS_line_indices["Net Worth"], :, :]
RentValue = PnL[PnL_line_indices["Rent"], :, :]
PayRollValue = PnL[PnL_line_indices["Payroll Expense"], :, :]



#print(Sales)

In [53]:
ROIRatio = PATValue / TotalEquityValue
ROTARatio = PATValue / TotalNetAssetsValue
CurrentRatio = TotalCurrentAssetsValue / TotalCurrentLiabilitiesValue
QuickRatio = (TotalCurrentAssetsValue - InventoryValue) / TotalCurrentLiabilitiesValue
WorkingCapitalSalesRatio = (TotalCurrentAssetsValue - TotalCurrentLiabilitiesValue) / SalesValue
InterestCoverRatio = PBITValue / InterestValue
DebtToEquityRatio = DebtValue / TotalEquityValue
LeverageRatio = TotalEquityValue / (DebtValue + TotalEquityValue)
TotalIncomeValue = SalesValue
TotalCostofSalesValue = DirectCostofSalesValue
GrossProfitValue = SalesValue - DirectCostofSalesValue
ROERatio = PATValue / TotalEquityValue
ROCERatio = (PBITValue + DebtValue) / TotalEquityValue
TotalLoanBalanceValue = DebtValue
TotalRevenueValue = SalesValue
BlendedTermInterestRate =  InterestValue / DebtValue
#ChangeInInventoryToChangeInSales = 
ClosingCashBalanceValue =  CashValue
HighDividendReleaseRatio = DividendValue / TotalEquityValue                                            
LargeVATBillToCapitalRatio =  TaxValue / TotalEquityValue    
MarginRate = GrossProfitValue / SalesValue
LoansToSalesRatio = DebtValue / SalesValue
#NetWorthValue =                                           
PayRollToSalesRatio = PayRollValue / SalesValue
RentToSalesRatio = RentValue / SalesValue    
VolitileEarningsValue = EarningsValue / TotalEquityValue                                            
#WorkingCapitaltoSalesRatio =     

first_mth = np.empty((1, len(companies_s)))
SalesGrowthRate =  np.concatenate((first_mth, SalesValue[1:, :] - SalesValue[:-1, :]), axis=0)
InventoryGrowthRate =  np.concatenate((first_mth, InventoryValue[1:, :] - InventoryValue[:-1, :]), axis=0) 

ChangeInInventoryToChangeInSales = np.empty_like(SalesGrowthRate)
mask = (SalesGrowthRate == 0)
ChangeInInventoryToChangeInSales[mask] = np.zeros(np.shape(ChangeInInventoryToChangeInSales))[mask]
ChangeInInventoryToChangeInSales[~mask] = InventoryGrowthRate[~mask]/SalesGrowthRate[~mask]

StockDaysValue = np.empty_like(DirectCostofSalesValue)
mask = (DirectCostofSalesValue == 0)
StockDaysValue[mask] = np.zeros(np.shape(StockDaysValue))[mask]
StockDaysValue[~mask] = (InventoryValue[~mask] * 30)/DirectCostofSalesValue[~mask]

In [54]:
#print(BS_key_lines[BS_key_line_items.index("Total Short-term Assets"), :, :] )
print(BS_key_line_items.index("Total Short-term Assets") )

3

In [57]:
Allpnl_array = np.concatenate((SalesValue, 
                               DirectCostofSalesValue,
                               TotalCurrentAssetsValue,
                               TotalCurrentLiabilitiesValue,
                               TotalEquityValue,
                               LongTermLiabilitiesValue,
                               OperatingExpensesValue,
                               TotalNetAssetsValue,
                               TotalFixedAssetValue,
                               TotalIncomeValue,
                               OtherIncomeValue,
                               OwnersFundsValue,
                               SalesValue,
                               OperatingCostsValue,
                               PBITValue,
                               InterestValue,
                               TaxValue,
                               PATValue,
                               DividendValue,
                               RetainedEarningsValue,
                               OrdinaryShareNumber,
                               OrdinarySharePriceValue,
                               ROTARatio,
                               CurrentRatio,
                               QuickRatio,
                               WorkingCapitalSalesRatio,
                               InterestCoverRatio,
                               DebtToEquityRatio,
                               LeverageRatio,
                               TotalIncomeValue,
                               TotalCostofSalesValue,
                               GrossProfitValue,
                               ROERatio,
                               ROCERatio,
                               TotalLoanBalanceValue,
                               TotalRevenueValue,
                               BlendedTermInterestRate ,
                               ChangeInInventoryToChangeInSales , 
                               ClosingCashBalanceValue  ,   
                               HighDividendReleaseRatio ,                                             
                               LargeVATBillToCapitalRatio ,                                             
                               LoansToSalesRatio , 
                               NetWorthValue   ,                                           
                               PayRollToSalesRatio,
                               RentToSalesRatio ,                                             
                               StockDaysValue  ,                                            
                               VolitileEarningsValue ,                                             
                               SalesGrowthRate
                              ), axis = 0)

In [58]:
np.shape(Allpnl_array)

(1728, 2)

In [59]:
number_months = 36
number_companies = len(companies_s)
number_metrics = np.shape(Allpnl_array)[0] // number_months


Allpnl_reshape_array = np.moveaxis(np.reshape(Allpnl_array, (number_metrics , number_months, number_companies)), 1, 2 )

print(Allpnl_reshape_array[:3, :, :10])

[[[34107.692310000006 7366.863904999999 11668.07721 11352.65446
   10145.04628 10248.79877 6649.280866 6393.539294 11636.24151
   9816.622937]
  [34107.692310000006 7366.863904999999 11668.07721 11352.65446
   10145.04628 10248.79877 6649.280866 6393.539294 11636.24151
   9816.622937]]

 [[0 4750 0 4750 0 4750 0 4750 0 4750]
  [0 4750 0 4750 0 4750 0 4750 0 4750]]

 [[53272.46377 40861.1117 39972.7196 34328.31045 30745.495160000002
   26641.54423 17605.50488 11481.95935 6744.490490000001 3987.857693]
  [53272.46377 40861.1117 39972.7196 34328.31045 30745.495160000002
   26641.54423 17605.50488 11481.95935 6744.490490000001 3987.857693]]]

In [60]:
party_id = np.array([0] * number_months).T
party_id_reshape= np.reshape(party_id, (number_months,1 ))
months_list = list(months)
months_array= np.array(months_list)
months_reshape= np.reshape(months_array, (number_months,1 ))
header = ["Party_id", "Date"] + [str("metric_") + str(i) for i in range(1, number_metrics + 1)]
header_array = np.array(header)
header_reshape= np.reshape(header_array, (1, 2 + number_metrics))
first_block = np.concatenate((party_id_reshape, months_reshape, (Allpnl_reshape_array[:,0,:]).T ), axis = 1)
#np.shape(header_reshape)
#np.shape(first_block)

Alloutput_reshape_array = np.concatenate( (header_reshape, first_block), axis = 0)          
for i in range(1, number_companies) :
    party_id = np.array([i] * number_months).T
    party_id_reshape= np.reshape(party_id, (number_months,1 ))
    next_block = np.concatenate((party_id_reshape, months_reshape, (Allpnl_reshape_array[:,i,:]).T ), axis = 1)
    Alloutput_reshape_array = np.concatenate( (Alloutput_reshape_array, next_block), axis=0)

        
#np.shape(Alloutput_reshape_array)            

print(Alloutput_reshape_array[:40,: 5])

[['Party_id' 'Date' 'metric_1' 'metric_2' 'metric_3']
 [0 '17-Dec' 34107.692310000006 0 53272.46377]
 [0 '18-Jan' 7366.863904999999 4750 40861.1117]
 [0 '18-Feb' 11668.07721 0 39972.7196]
 [0 '18-Mar' 11352.65446 4750 34328.31045]
 [0 '18-Apr' 10145.04628 0 30745.495160000002]
 [0 '18-May' 10248.79877 4750 26641.54423]
 [0 '18-Jun' 6649.280866 0 17605.50488]
 [0 '18-Jul' 6393.539294 4750 11481.95935]
 [0 '18-Aug' 11636.24151 0 6744.490490000001]
 [0 '18-Sep' 9816.622937 4750 3987.857693]
 [0 '18-Oct' 10149.70206 0 -3286.6657649999997]
 [0 '18-Nov' 17566.792019999997 4750 3069.67825]
 [0 '18-Dec' 32508.443310000002 0 9922.869469]
 [0 '19-Jan' 7021.444765 4750 -2611.096582]
 [0 '19-Feb' 11120.981829999999 0 -3693.0808869999996]
 [0 '19-Mar' 10820.34869 4750 -10229.66697]
 [0 '19-Apr' 9669.363111 0 -13498.974069999998]
 [0 '19-May' 9768.250832 4750 -19131.066730000002]
 [0 '19-Jun' 6337.507917 0 -27296.02863]
 [0 '19-Jul' 6093.757613000001 4750 -35000.69152]
 [0 '19-Aug' 11090.63886 0 -38851.03584]
 [0 '19-Sep' 9356.338955 4750 -43527.1789]
 [0 '19-Oct' 9673.800586 0 -49414.26613]
 [0 '19-Nov' 16743.1164 4750 -146211.9271]
 [0 '19-Dec' 27303.21234 0 -137648.2855]
 [0 '20-Jan' 5897.175560000001 4750 -151341.279]
 [0 '20-Feb' 9340.297395 0 -153739.8848]
 [0 '20-Mar' 9087.801443 4750 -161158.235]
 [0 '20-Apr' 8121.110929 0 -165843.3544]
 [0 '20-May' 8204.164812 4750 -171852.277]
 [0 '20-Jun' 5322.750239 0 -181284.1239]
 [0 '20-Jul' 5118.029076 4750 -188792.5867]
 [0 '20-Aug' 9314.812918000001 0 -194602.6417]
 [0 '20-Sep' 7858.207998999999 4750 -199348.3864]
 [0 '20-Oct' 8124.837879000001 0 -207283.9744]
 [0 '20-Nov' 14062.21941 4750 -204482.3621]
 [1 '17-Dec' 34107.692310000006 0 53272.46377]
 [1 '18-Jan' 7366.863904999999 4750 40861.1117]
 [1 '18-Feb' 11668.07721 0 39972.7196]]

In [61]:
header = ["Party_id", "Date"] + [str("metric_") + str(i) for i in range(1, number_metrics + 1)]
print(header)

['Party_id', 'Date', 'metric_1', 'metric_2', 'metric_3', 'metric_4', 'metric_5', 'metric_6', 'metric_7', 'metric_8', 'metric_9', 'metric_10', 'metric_11', 'metric_12', 'metric_13', 'metric_14', 'metric_15', 'metric_16', 'metric_17', 'metric_18', 'metric_19', 'metric_20', 'metric_21', 'metric_22', 'metric_23', 'metric_24', 'metric_25', 'metric_26', 'metric_27', 'metric_28', 'metric_29', 'metric_30', 'metric_31', 'metric_32', 'metric_33', 'metric_34', 'metric_35', 'metric_36', 'metric_37', 'metric_38', 'metric_39', 'metric_40', 'metric_41', 'metric_42', 'metric_43', 'metric_44', 'metric_45', 'metric_46', 'metric_47', 'metric_48']

In [62]:
import pandas as pd 


pd.DataFrame(Alloutput_reshape_array).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\Alloutput.csv", header=None, index=None)

metrics = Allpnl_reshape_array[:35, :,  -1]
np.shape(metrics)
#print(metrics)

(35, 2)

In [63]:
pd.DataFrame(Alloutput_reshape_array).to_sql('Alloutput', conn, if_exists='replace', index = False)

DatabaseError: Execution failed on sql 'DROP TABLE "Alloutput"': database table is locked

In [64]:

#placeholders for metrics to be sourced or calculated
CashflowChangeValue_array = np.reshape([0] * number_companies, (number_companies,1))
MLHighRiskSector_array = np.reshape([0] * number_companies, (number_companies,1))
LongSourcetoLongUseFunds_array = np.reshape([0] * number_companies, (number_companies,1))
NewDebtEquityToStockDebtEquity_array = np.reshape([0] * number_companies, (number_companies,1))
ShortSourceShortUseVsCurrentAssetsCurrentLiabilities_array = np.reshape([0] * number_companies, (number_companies,1))
OverseasCreditorsValueRatio_array = np.reshape([0] * number_companies, (number_companies,1))
NonOperationalAssetsValue_array = np.reshape([0] * number_companies, (number_companies,1))
DebtorDaysChangeValue_array = np.reshape([0] * number_companies, (number_companies,1))
CreditScoreAndNoSecurity_array = np.reshape([0] * number_companies, (number_companies,1))


#placeholders for metrics to be sourced or calculated
MetricLoanOutstandingLTVRatio_array = np.reshape([0] * number_companies, (number_companies,1))
MetricRiskMismatchPrice_array = np.reshape([0] * number_companies, (number_companies,1))


#print(CashflowChangeValue_array)

In [86]:

HasSustainableProfit = np.reshape((( MarginRate >= 0.10 ) * ( ROTARatio >= 1.30 ) *  ( ROTARatio <= 1.50 ))[-1, :], (number_companies, 1))

#print(MarginRate[:10,:])    
#print(ROTARatio[:10,:])    
#print(ROTARatio[:10,:])  
#print(HasSustainableProfit[:10,:])

In [87]:
np.shape(HasSustainableProfit)

(2, 1)

In [68]:
this_month_ROCE = ROCERatio[:-1, :]
last_month_ROCE = ROCERatio[1:, :]

MetricROCEChangeValue = np.empty_like(this_month_ROCE)
mask = (last_month_ROCE == 0)
MetricROCEChangeValue[mask] = np.zeros(np.shape(MetricROCEChangeValue))[mask]
MetricROCEChangeValue[~mask] = (this_month_ROCE[~mask] - last_month_ROCE[~mask])/last_month_ROCE[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricROCEChangeValue = np.reshape(np.concatenate((a, MetricROCEChangeValue), axis=0)[-1, :], (number_companies, 1))
#np.shape(MetricROCEChangeValue)


this_month_ROTA = ROTARatio[:-1, :]
last_month_ROTA = ROTARatio[1:, :]

MetricROTAChangeValue = np.empty_like(this_month_ROTA)
mask = (last_month_ROTA == 0)
MetricROTAChangeValue[mask] = np.zeros(np.shape(MetricROTAChangeValue))[mask]
MetricROTAChangeValue[~mask] = (this_month_ROCE[~mask] - last_month_ROTA[~mask])/last_month_ROTA[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricROTAChangeValue = np.reshape(np.concatenate((a, MetricROTAChangeValue), axis=0)[-1, :], (number_companies, 1))
#np.shape(MetricROTAChangeValue)


this_month_ROTA = ROTARatio[:-1, :]
last_month_ROTA = ROTARatio[1:, :]

MetricROTAChangeValue = np.empty_like(this_month_ROTA)
mask = (last_month_ROTA == 0)
MetricROTAChangeValue[mask] = np.zeros(np.shape(MetricROTAChangeValue))[mask]
MetricROTAChangeValue[~mask] = (this_month_ROCE[~mask] - last_month_ROTA[~mask])/last_month_ROTA[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricROTAChangeValue = np.reshape(np.concatenate((a, MetricROTAChangeValue), axis=0)[-1, :], (number_companies, 1))
#np.shape(MetricROTAChangeValue)

this_month_Margin = MarginRate[:-1, :]
last_month_Margin = MarginRate[1:, :]

MetricMarginChange = np.empty_like(this_month_Margin)
mask = (last_month_Margin == 0)
MetricMarginChange[mask] = np.zeros(np.shape(MetricMarginChange))[mask]
MetricMarginChange[~mask] = (this_month_Margin[~mask] - last_month_Margin[~mask])/last_month_Margin[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricMarginChange = np.reshape(np.concatenate((a, MetricMarginChange), axis=0)[-1, :], (number_companies, 1))

MetricChangeInInventoryToChangeInSales = np.reshape(ChangeInInventoryToChangeInSales[-1, :], (number_companies, 1))

In [70]:
np.shape(PATValue)

(36, 2)

In [71]:
#np.shape(MetricRiskMismatchPrice_array)
np.shape(np.reshape(np.array(commercial_df.iloc[:]["disqualified director"]), (number_companies,1)))
#np.shape(SalesGrowthRate)

(2, 1)

In [72]:
np.shape(invoice_df)
invoice_array = np.reshape(invoice_df, np.shape(invoice_df))
type(invoice_array)

unique_companies = np.unique(invoice_df["PartyId"])
unique_customers = np.unique(invoice_df["CustomerId"])
customer_concentration_ratio = [] 
sums = []
accum_sums = []
customer_concentration_ratios = []
last_sum = 0
for company in unique_companies :
   company_invoice_df = invoice_df[["GrossValue","CustomerId"]][invoice_df["PartyId"] == company ] 
   for customer in unique_customers :
      s = company_invoice_df["GrossValue"][company_invoice_df["CustomerId"] == customer].sum()
      sums.append(s)
   sums_rank = pd.Series(sums).rank()
   rank_2  = list(np.where(sums_rank == len(sums) - 2))[0]
   customer_concentration_ratio = max(sums / sums[rank_2[0]])
   customer_concentration_ratios.append(customer_concentration_ratio)

print(customer_concentration_ratios)    

MetricCustomerConcentrationRatios = np.reshape(customer_concentration_ratios, (number_companies, 1))
MetricSupplierConcentrationRatios = MetricCustomerConcentrationRatios

[1.0408319148007508, 1.0408319148007508]

In [73]:
print(MetricCustomerConcentrationRatios)

[[1.04083191]
 [1.04083191]]

In [74]:
# create metrics from commercial data
MetricDisqualifiedDirector = np.reshape(np.array(commercial_df.iloc[:]["disqualified director"]), (number_companies, 1))
MetricCCJDirector = np.reshape(np.array(commercial_df.iloc[:]["CCJ director"]), (number_companies, 1))
MetricBankcruptDirector = np.reshape(np.array(commercial_df.iloc[:]["bankcrupt director"]), (number_companies, 1))
MetricChangedDirector = np.reshape(np.array(commercial_df.iloc[:]["changed director"]), (number_companies, 1))
MetricNewBusinessDirector = np.reshape(np.array(commercial_df.iloc[:]["new business director"]), (number_companies, 1))
MetricRegionalEconomyIndex = np.reshape(np.array(commercial_df.iloc[:]["regional economy index"]), (number_companies, 1))


#metrics calculated from accounting data
MetricVolitileEarningsValue = np.reshape(VolitileEarningsValue[-1, :], (number_companies, 1))
MetricPATValue = np.reshape(PATValue[-1, :], (number_companies, 1))
MetricSalesGrowthRate = np.reshape(SalesGrowthRate[-1, :], (number_companies, 1))
MetricCurrentRatio = np.reshape(CurrentRatio[-1, :], (number_companies, 1))
MetricWorkingCapitalSalesRatio = np.reshape(WorkingCapitalSalesRatio[-1, :], (number_companies, 1))
MetricDebtToEquityRatio = np.reshape(DebtToEquityRatio[-1, :], (number_companies, 1))
MetricLoansToSalesRatio = np.reshape(LoansToSalesRatio[-1, :], (number_companies, 1))
MetricPayRollToSalesRatio = np.reshape(PayRollToSalesRatio[-1, :], (number_companies, 1))
MetricRentToSalesRatio = np.reshape(RentToSalesRatio[-1, :], (number_companies, 1))
MetricHighDividendReleaseRatio = np.reshape(HighDividendReleaseRatio[-1, :], (number_companies, 1))
MetricLargeVATBillToCapitalRatio = np.reshape(LargeVATBillToCapitalRatio[-1, :], (number_companies, 1))

In [84]:
np.shape(OverseasCreditorsValueRatio_array)

(2, 1)

In [75]:
np.shape(np.array(commercial_df.iloc[:]["disqualified director"]))
np.shape(CreditScoreAndNoSecurity_array)

(2, 1)

In [88]:
signals_array = np.concatenate((MetricDisqualifiedDirector,
                                MetricCCJDirector,
                                MetricBankcruptDirector,
                                CreditScoreAndNoSecurity_array,
                                MetricLoanOutstandingLTVRatio_array,
                                MetricChangedDirector,
                                MetricRiskMismatchPrice_array,
                                MetricVolitileEarningsValue,
                                MetricPATValue,
                                CashflowChangeValue_array,
                                MLHighRiskSector_array,
                                MetricROCEChangeValue,
                                MetricROTAChangeValue,
                                HasSustainableProfit,
                                MetricSalesGrowthRate,
                                MetricCurrentRatio,
                                MetricWorkingCapitalSalesRatio,
                                MetricDebtToEquityRatio,
                                LongSourcetoLongUseFunds_array,
                                NewDebtEquityToStockDebtEquity_array,
                                ShortSourceShortUseVsCurrentAssetsCurrentLiabilities_array,
                                MetricMarginChange,
                                MetricChangeInInventoryToChangeInSales,
                                MetricLoansToSalesRatio,
                                MetricPayRollToSalesRatio,
                                MetricRentToSalesRatio,
                                OverseasCreditorsValueRatio_array,
                                NonOperationalAssetsValue_array,
                                MetricNewBusinessDirector,
                                MetricHighDividendReleaseRatio,
                                MetricSupplierConcentrationRatios,
                                MetricCustomerConcentrationRatios,
                                MetricRegionalEconomyIndex,
                                DebtorDaysChangeValue_array,
                                MetricLargeVATBillToCapitalRatio
                                ), axis = 0)





signals_reshape_array = np.reshape(signals_array, (np.shape(signals_array)[0]// 2, 2))
print(signals_reshape_array)

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0.8117120950423786 0.8117120950423786]
 [-4623.885446 -4623.885446]
 [0 0]
 [0 0]
 [0.17282565358114474 0.17282565358114474]
 [147.43649272436036 147.43649272436036]
 [False False]
 [5937.381530999999 5937.381530999999]
 [-0.700387599843812 -0.700387599843812]
 [-35.30298792998281 -35.30298792998281]
 [1.181309163942098 1.181309163942098]
 [0 0]
 [0 0]
 [0 0]
 [0.5100824831188121 0.5100824831188121]
 [0.0 0.0]
 [19.834706874339687 19.834706874339687]
 [0.06826802882319698 0.06826802882319698]
 [0.09244628903141258 0.09244628903141258]
 [0 0]
 [0 0]
 [1 0]
 [-0.42352974470891225 -0.42352974470891225]
 [1.0408319148007508 1.0408319148007508]
 [1.0408319148007508 1.0408319148007508]
 [8 6]
 [0 0]
 [-0.0006212975883659394 -0.0006212975883659394]]

In [89]:
thresholds_limits = np.concatenate((thresholdsll_df.iloc[1:,1:], thresholdsul_df.iloc[1:,1:]), axis=0)
rows, columns = np.shape(thresholds_limits)

threshold_limits_reshaped = np.reshape(thresholds_limits, (2, int(rows / 2), columns))

np.shape(threshold_limits_reshaped)
print(threshold_limits_reshaped)

[[[  nan   nan  0.     nan   nan   nan   nan   nan]
  [  nan   nan  0.     nan   nan   nan   nan   nan]
  [  nan   nan  0.     nan   nan   nan   nan   nan]
  [  nan   nan  0.3    nan   nan   nan   nan   nan]
  [  nan   nan  0.     nan   nan   nan   nan   nan]
  [ 2.     nan   nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan -0.33   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan -0.2    nan   nan]
  [  nan -0.2    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan   nan  1.     nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan  1.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan  0.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan  0.5    nan   nan   nan   nan]
  [  nan  0.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan  0.5    nan   nan   nan   nan]
  [  nan  0.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan   nan   nan  0.2 ]
  [ 5.     nan   nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan   nan  1.5    nan]
  [  nan   nan   nan   nan   nan   nan   nan  0.7 ]
  [  nan   nan   nan   nan   nan   nan   nan  3.  ]
  [  nan   nan   nan   nan   nan   nan   nan  0.7 ]
  [  nan   nan   nan   nan   nan   nan  0.5    nan]
  [  nan   nan   nan   nan   nan   nan  0.5    nan]
  [  nan   nan   nan   nan   nan   nan   nan  0.5 ]
  [  nan   nan   nan   nan   nan   nan  0.5    nan]
  [  nan   nan   nan   nan  1.5    nan   nan   nan]
  [  nan   nan   nan   nan  1.5    nan   nan   nan]
  [  nan   nan   nan   nan  1.5    nan   nan   nan]
  [  nan  0.5    nan   nan   nan   nan   nan   nan]
  [  nan  0.4    nan   nan   nan   nan   nan   nan]]

 [[ 0.    0.    0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.45  0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
  [ 3.    0.    0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.   -0.5   0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.   -0.3   0.    0.  ]
  [ 0.   -0.3   0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.    1.5   0.  ]
  [ 0.    0.    0.    0.    0.    0.75  0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.75  0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.75  0.    0.  ]
  [ 0.    2.25  0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.75  0.    0.  ]
  [ 0.    0.75  0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.75  0.    0.    0.    0.  ]
  [ 0.    0.75  0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.75  0.    0.    0.    0.  ]
  [ 0.    0.75  0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.    0.3 ]
  [ 3.33  0.    0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.    0.    0.    2.25  0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.    1.05]
  [ 0.    0.    0.    0.    0.    0.    0.    4.5 ]
  [ 0.    0.    0.    0.    0.    0.    0.    1.05]
  [ 0.    0.    0.    0.    0.    0.    0.75  0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.75  0.  ]
  [ 0.    0.    0.    0.    0.    0.    0.    0.75]
  [ 0.    0.    0.    0.    0.    0.    0.75  0.  ]
  [ 0.    0.    0.    0.    2.25  0.    0.    0.  ]
  [ 0.    0.    0.    0.    2.25  0.    0.    0.  ]
  [ 0.    0.    0.    0.    2.25  0.    0.    0.  ]
  [ 0.    0.75  0.    0.    0.    0.    0.    0.  ]
  [ 0.    0.6   0.    0.    0.    0.    0.    0.  ]]]

In [92]:
thresholds_pts = np.concatenate((thresholdslpts_df.iloc[1:,1:], thresholdsupts_df.iloc[1:,1:]), axis=0)
rows, columns = np.shape(thresholds_pts)

threshold_pts_reshaped = np.reshape(thresholds_pts, (2, int(rows / 2), columns))

np.shape(threshold_pts_reshaped)

print(threshold_pts_reshaped)

[[[nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [ 3. nan nan nan nan nan nan nan]
  [nan nan nan  3. nan nan nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan 10. nan nan nan nan nan nan]
  [nan nan nan nan nan  0.  3. nan]
  [nan nan nan nan nan  3. nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan  3. nan nan nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan  3. nan nan nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan nan nan nan nan  3.]
  [ 3. nan nan nan nan nan nan nan]
  [nan nan nan nan nan nan  3. nan]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan  3. nan]
  [nan nan nan nan nan nan  3. nan]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan  3. nan]
  [nan nan nan nan  3. nan nan nan]
  [nan nan nan nan  3. nan nan nan]
  [nan nan nan nan  3. nan nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan  3. nan nan nan nan nan nan]]

 [[nan nan  5. nan nan nan nan nan]
  [nan nan  5. nan nan nan nan nan]
  [nan nan  5. nan nan nan nan nan]
  [nan nan  5. nan nan nan nan nan]
  [nan nan  5. nan nan nan nan nan]
  [ 5. nan nan nan nan nan nan nan]
  [nan nan nan  5. nan nan nan nan]
  [nan nan nan nan nan  5. nan nan]
  [nan 20. nan nan nan nan nan nan]
  [nan nan nan nan nan nan  5. nan]
  [nan nan nan nan nan  5. nan nan]
  [nan nan nan nan nan  5. nan nan]
  [nan nan nan nan nan  5. nan nan]
  [nan  5. nan nan nan nan nan nan]
  [nan nan nan nan nan  5. nan nan]
  [nan  5. nan nan nan nan nan nan]
  [nan nan nan  5. nan nan nan nan]
  [nan  5. nan nan nan nan nan nan]
  [nan nan nan  5. nan nan nan nan]
  [nan  5. nan nan nan nan nan nan]
  [nan nan nan nan nan nan nan  5.]
  [ 5. nan nan nan nan nan nan nan]
  [nan nan nan nan nan nan  5. nan]
  [nan nan nan nan nan nan nan  5.]
  [nan nan nan nan nan nan nan  5.]
  [nan nan nan nan nan nan nan  5.]
  [nan nan nan nan nan nan  5. nan]
  [nan nan nan nan nan nan  5. nan]
  [nan nan nan nan nan nan nan  5.]
  [nan nan nan nan nan nan  5. nan]
  [nan nan nan nan  5. nan nan nan]
  [nan nan nan nan  5. nan nan nan]
  [nan nan nan nan  5. nan nan nan]
  [nan  5. nan nan nan nan nan nan]
  [nan nan  5. nan nan nan nan nan]]]

In [90]:
review_trigger_levels = np.transpose(np.array(review_trigger_levels_df.iloc[:,1:]))
print(review_trigger_levels)

[[4.  4.  0.5 3.  4.  4.  3.  4. ]]

In [93]:
metrics = signals_reshape_array
number_limits, number_metrics, number_risks = np.shape(threshold_limits_reshaped)

number_companies = 2
company = 0
lower_limit = 0
upper_limit = 1
lower_breach = np.zeros((number_metrics, number_risks, number_companies))
lower_score = np.zeros((number_metrics, number_risks, number_companies))
upper_breach = np.zeros((number_metrics, number_risks, number_companies))
upper_score = np.zeros((number_metrics, number_risks, number_companies))
company_lower_risk_score = np.zeros((number_risks, number_companies))
for company in range(number_companies) :
   for risk in range(number_risks) :
      lower_breach[:, risk, company] = metrics[:, company] > threshold_limits_reshaped[lower_limit, :, risk]
      lower_score[:, risk, company] =  lower_breach[:, risk, company] * threshold_pts_reshaped[lower_limit, :, risk]  
      upper_breach[:, risk, company] = metrics[:, company] > threshold_limits_reshaped[upper_limit, :, risk]
      upper_score[:, risk, company] =  upper_breach[:, risk, company] * threshold_pts_reshaped[upper_limit, :, risk]  
      final_score = np.maximum(lower_score, upper_score)   
company_final_risk_score = np.nanmean(final_score, axis=0) 
print(company_final_risk_score)

[[0.         0.        ]
 [0.83333333 0.83333333]
 [3.         0.        ]
 [1.66666667 1.66666667]
 [1.66666667 1.66666667]
 [3.         3.        ]
 [0.         0.        ]
 [2.         1.        ]]

<ipython-input-93-dd77b566150d>:15: RuntimeWarning: invalid value encountered in greater
  lower_breach[:, risk, company] = metrics[:, company] > threshold_limits_reshaped[lower_limit, :, risk]

In [94]:
risk_profile = np.zeros((number_risks, number_companies))
for company in range(number_companies) :
   risk_profile[:, company] = company_final_risk_score[:, company] > review_trigger_levels
print(risk_profile)

[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

In [95]:
risk_signals = np.zeros((number_metrics, number_companies))
for company in range(number_companies) :
   risk_signals[:, company] = np.matmul(np.nan_to_num(final_score[:,:,company]), np.nan_to_num(np.transpose(company_final_risk_score[:, company]))) > 0
print(risk_signals)


header =  ["Party_id", "ValiDate", "DateCreated", "Description", "DescriptionDetail", "Action", "ActionData", "Weigthing", "Status", "Narrative", "QueueType"]
block = np.reshape(header, (1, 11))
for company in range(number_companies) :
    party_id = []
    ValidDate=[]
    DateCreated =[]
    Description = []
    DescriptionDetail = []
    Action = []
    ActionData = []
    Weighting = []
    Status = []
    Narrative = []
    QueueType = []
    count_signals = 0
    for metric in range(number_metrics) :
       if risk_signals[metric, company] > 0 :
          party_id = np.append(party_id, str(company))
          ValidDate= np.append(ValidDate, ["8/31/2020  12:00:00 AM"])
          DateCreated = np.append(DateCreated,["8/31/2020  12:00:00 AM"]) 
          Description = np.append(Description, signal_narrative_df['description detail'][metric])
          DescriptionDetail = np.append(DescriptionDetail, signal_narrative_df['description'][metric])
          Action =  np.append(Action, signal_narrative_df['action'][metric]) 
          ActionData = np.append(ActionData, [" "])
          Weighting = np.append(Weighting, [" "])
          Status = np.append(Status, ["Open"])
          if signal_narrative_df['insert'][metric] == 0 :
            Narrative = np.append(Narrative, signal_narrative_df['narrative'][metric])
          else :
            Narrative = np.append(Narrative, signal_narrative_df['narrative'][metric] + " {} ".format(metrics[metric, company]) +  signal_narrative_df['narrative2'][metric])
          QueueType = np.append(QueueType, signal_narrative_df['risk'][metric])
          count_signals += 1  
       next_block = np.concatenate((party_id, ValidDate, DateCreated, Description, DescriptionDetail, Action, ActionData, Weighting, Status, Narrative, QueueType), axis = 0)  
       cols = count_signals
       rows = 11
       next_block_reshape = np.reshape(next_block, (rows, cols))    
       next_block_reshape_transpose = next_block_reshape.T
    block = np.concatenate((block, next_block_reshape_transpose), axis=0)

print(block)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[['Party_id' 'ValiDate' 'DateCreated' 'Description' 'DescriptionDetail'
  'Action' 'ActionData' 'Weigthing' 'Status' 'Narrative' 'QueueType']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'A director has been disquaified.  ' 'Credit Risk' 'ViewDirectors' ' '
  ' ' 'Open'
  'A named director of the business has been registered as disqualified within the last 30 days.  This is in breach of credit policy and immediate intervention is required.'
  'Credit']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'A director has sanctioned with a CCJ. ' 'Credit Risk'
  'ViewPublicRecords' ' ' ' ' 'Open'
  'A named director has registered as santioned with a CCJ within the last 30days.   This is in breach of credit policy and immediate intervention is required.'
  'Credit']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'A director has be made bankcrupt.  ' 'Credit Risk' 'ViewPublicRecords'
  ' ' ' ' 'Open'
  'A named director has be registered bankcrupt within the past 30days. This is in breach of credit policy and immediate intervention is required.'
  'Credit']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'The relative risk of the firm is misaligned with the relative price of its loan. '
  'Conduct Risk' 'ViewPnL' ' ' ' ' 'Open'
  'Firm, with in the portfolio, is in a low decile by risk and high decile by price.   This needs to be considered in the context of treat customer fairly to determine if redress or remediation is required.'
  'Conduct']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'Earnings are volitile' 'Capital Risk' 'ViewCashFlow' ' ' ' ' 'Open'
  'Over the past 36month, highest net cash outflow in any month reached 0.8117120950423786 of opening capital reserve in the month.'
  'Capital']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM' 'Fall in ROTA'
  'Trade Risk' 'ViewBS' ' ' ' ' 'Open'
  'Return On Total Assets (ROTA) has dropped by 147.43649272436036 since previous month.  This is a key efficiency measure.'
  'Trade']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'High growth business' 'Liquidity Risk' 'ViewPnL' ' ' ' ' 'Open'
  'Last 3months sales performance has grown 5937.381530999999 .  This is a high measure and there is a risk of over trading'
  'Liquidity']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM' 'Gearing'
  'Capital Risk' 'ViewBS' ' ' ' ' 'Open'
  'Gearing of firm has increased and debt to equity ratio is above 50% at 1.181309163942098 .'
  'Capital']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'sales have increase but no equivalent change in inventory is seen'
  'AML Risk' 'ViewPnLAndBS' ' ' ' ' 'Open'
  'Change in sales to change in inventory moved to a ratio of 19.834706874339687 over the last month.  Increased sales with out and corresponding increase in inventory could be a cause to investigate.'
  'AML']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'High value non operation assets have entered the Balance Sheet'
  'AML Risk' 'ViewBS' ' ' ' ' 'Open'
  'High value non operation assets  - such as boats/ villas or collectors cars - appear on the Balance Sheet.   This could be cause for investigation. '
  'AML']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'High proporton of sales are concentrated in a small number of customers'
  'Contagion Risk' 'ViewBS' ' ' ' ' 'Open'
  'High proporton of sales are concentrated in a small number of customers.   In the event of customer business failing there could be disproportinate impact on the firm.'
  'Contagion']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'The relative risk of the firm is misaligned with the relative price of its loan. '
  'Conduct Risk' 'ViewPnL' ' ' ' ' 'Open'
  'Firm, with in the portfolio, is in a low decile by risk and high decile by price.   This needs to be considered in the context of treat customer fairly to determine if redress or remediation is required.'
  'Conduct']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'Earnings are volitile' 'Capital Risk' 'ViewCashFlow' ' ' ' ' 'Open'
  'Over the past 36month, highest net cash outflow in any month reached 0.8117120950423786 of opening capital reserve in the month.'
  'Capital']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM' 'Fall in ROTA'
  'Trade Risk' 'ViewBS' ' ' ' ' 'Open'
  'Return On Total Assets (ROTA) has dropped by 147.43649272436036 since previous month.  This is a key efficiency measure.'
  'Trade']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'High growth business' 'Liquidity Risk' 'ViewPnL' ' ' ' ' 'Open'
  'Last 3months sales performance has grown 5937.381530999999 .  This is a high measure and there is a risk of over trading'
  'Liquidity']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM' 'Gearing'
  'Capital Risk' 'ViewBS' ' ' ' ' 'Open'
  'Gearing of firm has increased and debt to equity ratio is above 50% at 1.181309163942098 .'
  'Capital']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'sales have increase but no equivalent change in inventory is seen'
  'AML Risk' 'ViewPnLAndBS' ' ' ' ' 'Open'
  'Change in sales to change in inventory moved to a ratio of 19.834706874339687 over the last month.  Increased sales with out and corresponding increase in inventory could be a cause to investigate.'
  'AML']
 ['1' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'High proporton of sales are concentrated in a small number of customers'
  'Contagion Risk' 'ViewBS' ' ' ' ' 'Open'
  'High proporton of sales are concentrated in a small number of customers.   In the event of customer business failing there could be disproportinate impact on the firm.'
  'Contagion']]

In [96]:

pd.DataFrame(block).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\signals.csv", header=None, index=None)

In [501]:
pd.DataFrame(block).to_sql('signals', conn, if_exists='replace', index = False)

In [97]:
header = [ 
"Id",
"PartyId",
"QueueType",
"DateCreated",
"Status",
"DateClosed"
]

header_queue = np.reshape(header, (1, len(header)))

In [98]:
block_queue = block[1:,[0, 10, 2]]
unique_block_queue = np.unique(block_queue, axis=0)
print(unique_block_queue)

[['0' 'AML' '8/31/2020  12:00:00 AM']
 ['0' 'Capital' '8/31/2020  12:00:00 AM']
 ['0' 'Conduct' '8/31/2020  12:00:00 AM']
 ['0' 'Contagion' '8/31/2020  12:00:00 AM']
 ['0' 'Credit' '8/31/2020  12:00:00 AM']
 ['0' 'Liquidity' '8/31/2020  12:00:00 AM']
 ['0' 'Trade' '8/31/2020  12:00:00 AM']
 ['1' 'AML' '8/31/2020  12:00:00 AM']
 ['1' 'Capital' '8/31/2020  12:00:00 AM']
 ['1' 'Conduct' '8/31/2020  12:00:00 AM']
 ['1' 'Contagion' '8/31/2020  12:00:00 AM']
 ['1' 'Liquidity' '8/31/2020  12:00:00 AM']
 ['1' 'Trade' '8/31/2020  12:00:00 AM']]

In [99]:
rows, cols = np.shape(unique_block_queue)
id = np.reshape([i for i in range(rows)], (rows,1)) 
#print(id)
status = np.reshape(["New"] * rows, (rows,1)) 
#print(status)
dateclosed = np.reshape([""] * rows, (rows,1)) 
np.shape(id)

(13, 1)

In [100]:
block_queue_out = np.concatenate ((header_queue, np.concatenate ((id, unique_block_queue, status, dateclosed), axis= 1)), axis=0)
print(block_queue_out)

[['Id' 'PartyId' 'QueueType' 'DateCreated' 'Status' 'DateClosed']
 ['0' '0' 'AML' '8/31/2020  12:00:00 AM' 'New' '']
 ['1' '0' 'Capital' '8/31/2020  12:00:00 AM' 'New' '']
 ['2' '0' 'Conduct' '8/31/2020  12:00:00 AM' 'New' '']
 ['3' '0' 'Contagion' '8/31/2020  12:00:00 AM' 'New' '']
 ['4' '0' 'Credit' '8/31/2020  12:00:00 AM' 'New' '']
 ['5' '0' 'Liquidity' '8/31/2020  12:00:00 AM' 'New' '']
 ['6' '0' 'Trade' '8/31/2020  12:00:00 AM' 'New' '']
 ['7' '1' 'AML' '8/31/2020  12:00:00 AM' 'New' '']
 ['8' '1' 'Capital' '8/31/2020  12:00:00 AM' 'New' '']
 ['9' '1' 'Conduct' '8/31/2020  12:00:00 AM' 'New' '']
 ['10' '1' 'Contagion' '8/31/2020  12:00:00 AM' 'New' '']
 ['11' '1' 'Liquidity' '8/31/2020  12:00:00 AM' 'New' '']
 ['12' '1' 'Trade' '8/31/2020  12:00:00 AM' 'New' '']]

In [101]:
pd.DataFrame(block_queue_out).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\queuev2.csv", header=None, index=None)

In [500]:
pd.DataFrame(block_queue_out).to_sql('queuev2', conn, if_exists='replace', index = False)

In [102]:
#cashflow
print(BS_df)

                          Line item        17-Dec       18-Jan        18-Feb  \
0                            Assets           NaN          NaN           NaN
1                 Short-term Assets           NaN          NaN           NaN
2                              Cash   34272.46377   26611.1117   25722.71960
3               Accounts Receivable           NaN          NaN           NaN
4                         Inventory   19000.00000   14250.0000   14250.00000
5           Other Short-term Assets           NaN          NaN           NaN
6           Total Short-term Assets   53272.46377   40861.1117   39972.71960
7                  Long-term Assets       0.00000       0.0000       0.00000
8                    Capital Assets       0.00000       0.0000       0.00000
9          Accumulated Depreciation       0.00000       0.0000       0.00000
10           Total Long-term Assets       0.00000       0.0000       0.00000
11                     Total Assets   53272.46377   40861.1117   39972.71960
12          Liabilities and Capital           NaN          NaN           NaN
13                 Accounts Payable    8540.00000    6058.0000    5316.00000
14                 Short-term Notes  300000.00000  300000.0000  299380.00000
15     Other Short-term Liabilities           NaN          NaN           NaN
16  Subtotal Short-term Liabilities  308540.00000  306058.2262  304696.00000
17            Long-term Liabilities           NaN          NaN           NaN
18                Total Liabilities  308540.00000  306058.2262  304696.00000
19                  Paid in Capital   18299.00000   18299.0000   18299.00000
20                   Dividends paid       0.00000       0.0000       0.00000
21                Retained Earnings  -34743.00000  -34743.0000  -34743.00000
22                         Earnings   22934.57175   17293.3935   22692.87675
23                    Total Capital    6490.57175     849.3935    6248.87675
24    Total Liabilities and Capital  315030.57180  306907.6197  310944.87680
25                        Net Worth -255267.53620 -265197.1145 -264723.28040
26                           Assets           NaN          NaN           NaN
27                Short-term Assets           NaN          NaN           NaN
28                             Cash   34272.46377   26611.1117   25722.71960
29              Accounts Receivable           NaN          NaN           NaN
30                        Inventory   19000.00000   14250.0000   14250.00000
31          Other Short-term Assets           NaN          NaN           NaN
32          Total Short-term Assets   53272.46377   40861.1117   39972.71960
33                 Long-term Assets       0.00000       0.0000       0.00000
34                   Capital Assets       0.00000       0.0000       0.00000
35         Accumulated Depreciation       0.00000       0.0000       0.00000
36           Total Long-term Assets       0.00000       0.0000       0.00000
37                     Total Assets   53272.46377   40861.1117   39972.71960
38          Liabilities and Capital           NaN          NaN           NaN
39                 Accounts Payable    8540.00000    6058.0000    5316.00000
40                 Short-term Notes  300000.00000  300000.0000  299380.00000
41     Other Short-term Liabilities           NaN          NaN           NaN
42  Subtotal Short-term Liabilities  308540.00000  306058.2262  304696.00000
43            Long-term Liabilities           NaN          NaN           NaN
44                Total Liabilities  308540.00000  306058.2262  304696.00000
45                  Paid in Capital   18299.00000   18299.0000   18299.00000
46                   Dividends paid       0.00000       0.0000       0.00000
47                Retained Earnings  -34743.00000  -34743.0000  -34743.00000
48                         Earnings   22934.57175   17293.3935   22692.87675
49                    Total Capital    6490.57175     849.3935    6248.87675
50    Total Liabilities and Capital  315030.57180  306907.6197  310944.87680
51                        Net Worth -255267.53620 -265197.1145 -264723.28040

          18-Mar        18-Apr        18-May        18-Jun         18-Jul  \
0            NaN           NaN           NaN           NaN            NaN
1            NaN           NaN           NaN           NaN            NaN
2    24828.31045   21245.49516   19516.54423   10480.50488    4356.959354
3            NaN           NaN           NaN           NaN            NaN
4     9500.00000    9500.00000    7125.00000    7125.00000    7125.000000
5            NaN           NaN           NaN           NaN            NaN
6    34328.31045   30745.49516   26641.54423   17605.50488   11481.959350
7        0.00000       0.00000       0.00000       0.00000       0.000000
8        0.00000       0.00000       0.00000       0.00000       0.000000
9        0.00000       0.00000       0.00000       0.00000       0.000000
10       0.00000       0.00000       0.00000       0.00000       0.000000
11   34328.31045   30745.49516   26641.54423   17605.50488   11481.959350
12           NaN           NaN           NaN           NaN            NaN
13    7213.00000    4943.00000    9354.00000    5527.00000   10420.000000
14  298760.00000  298140.00000  297520.00000  296900.00000  296280.000000
15           NaN           NaN           NaN           NaN            NaN
16  305973.00000  303083.00000  306874.00000  302427.00000  306700.000000
17           NaN           NaN           NaN           NaN            NaN
18  305973.00000  303083.00000  306874.00000  302427.00000  306700.000000
19   18299.00000   18299.00000   18299.00000   18299.00000   18299.000000
20       0.00000       0.00000       0.00000       0.00000       0.000000
21  -34743.00000  -34743.00000  -34743.00000  -34743.00000  -34743.000000
22   21046.77150   25827.32775   23792.54550   24595.67475   19778.965500
23    4602.77150    9383.32775    7348.54550    8151.67475    3334.965500
24  310575.77150  312466.32780  314222.54550  310578.67480  310034.965500
25 -271644.68960 -272337.50480 -280232.45580 -284821.49510 -295218.040600
26           NaN           NaN           NaN           NaN            NaN
27           NaN           NaN           NaN           NaN            NaN
28   24828.31045   21245.49516   19516.54423   10480.50488    4356.959354
29           NaN           NaN           NaN           NaN            NaN
30    9500.00000    9500.00000    7125.00000    7125.00000    7125.000000
31           NaN           NaN           NaN           NaN            NaN
32   34328.31045   30745.49516   26641.54423   17605.50488   11481.959350
33       0.00000       0.00000       0.00000       0.00000       0.000000
34       0.00000       0.00000       0.00000       0.00000       0.000000
35       0.00000       0.00000       0.00000       0.00000       0.000000
36       0.00000       0.00000       0.00000       0.00000       0.000000
37   34328.31045   30745.49516   26641.54423   17605.50488   11481.959350
38           NaN           NaN           NaN           NaN            NaN
39    7213.00000    4943.00000    9354.00000    5527.00000   10420.000000
40  298760.00000  298140.00000  297520.00000  296900.00000  296280.000000
41           NaN           NaN           NaN           NaN            NaN
42  305973.00000  303083.00000  306874.00000  302427.00000  306700.000000
43           NaN           NaN           NaN           NaN            NaN
44  305973.00000  303083.00000  306874.00000  302427.00000  306700.000000
45   18299.00000   18299.00000   18299.00000   18299.00000   18299.000000
46       0.00000       0.00000       0.00000       0.00000       0.000000
47  -34743.00000  -34743.00000  -34743.00000  -34743.00000  -34743.000000
48   21046.77150   25827.32775   23792.54550   24595.67475   19778.965500
49    4602.77150    9383.32775    7348.54550    8151.67475    3334.965500
50  310575.77150  312466.32780  314222.54550  310578.67480  310034.965500
51 -271644.68960 -272337.50480 -280232.45580 -284821.49510 -295218.040600

          18-Aug  ...         20-Feb        20-Mar         20-Apr  \
0            NaN  ...            NaN           NaN            NaN
1            NaN  ...            NaN           NaN            NaN
2     -380.50951  ... -160864.884800 -168283.23500 -172968.354400
3            NaN  ...            NaN           NaN            NaN
4     7125.00000  ...    7125.000000    7125.00000    7125.000000
5            NaN  ...            NaN           NaN            NaN
6     6744.49049  ... -153739.884800 -161158.23500 -165843.354400
7        0.00000  ...       0.000000       0.00000       0.000000
8        0.00000  ...       0.000000       0.00000       0.000000
9        0.00000  ...       0.000000       0.00000       0.000000
10       0.00000  ...       0.000000       0.00000       0.000000
11    6744.49049  ... -153739.884800 -161158.23500 -165843.354400
12           NaN  ...            NaN           NaN            NaN
13    6004.00000  ...    4689.678284    6363.17710    4360.624484
14  295660.00000  ...  284500.000000  283880.00000  283260.000000
15           NaN  ...            NaN           NaN            NaN
16  301664.00000  ...  289189.678300  290243.17710  287620.624500
17           NaN  ...            NaN           NaN            NaN
18  301664.00000  ...  289189.678300  290243.17710  287620.624500
19   18299.00000  ...   18299.000000   18299.00000   18299.000000
20       0.00000  ... -100000.000000 -100000.00000 -100000.000000
21  -34743.00000  ...  126157.831500  126157.83150  126157.831500
22   27580.16775  ...   66653.210610   75533.94662   90101.314670
23   11136.16775  ...  111110.042100  119990.77810  134558.146200
24  312800.16780  ...  400299.720400  410233.95520  422178.770600
25 -294919.50950  ... -442929.563100 -451401.41200 -453463.978900
26           NaN  ...            NaN           NaN            NaN
27           NaN  ...            NaN           NaN            NaN
28    -380.50951  ... -160864.884800 -168283.23500 -172968.354400
29           NaN  ...            NaN           NaN            NaN
30    7125.00000  ...    7125.000000    7125.00000    7125.000000
31           NaN  ...            NaN           NaN            NaN
32    6744.49049  ... -153739.884800 -161158.23500 -165843.354400
33       0.00000  ...       0.000000       0.00000       0.000000
34       0.00000  ...       0.000000       0.00000       0.000000
35       0.00000  ...       0.000000       0.00000       0.000000
36       0.00000  ...       0.000000       0.00000       0.000000
37    6744.49049  ... -153739.884800 -161158.23500 -165843.354400
38           NaN  ...            NaN           NaN            NaN
39    6004.00000  ...    4689.678284    6363.17710    4360.624484
40  295660.00000  ...  284500.000000  283880.00000  283260.000000
41           NaN  ...            NaN           NaN            NaN
42  301664.00000  ...  289189.678300  290243.17710  287620.624500
43           NaN  ...            NaN           NaN            NaN
44  301664.00000  ...  289189.678300  290243.17710  287620.624500
45   18299.00000  ...   18299.000000   18299.00000   18299.000000
46       0.00000  ... -100000.000000 -100000.00000 -100000.000000
47  -34743.00000  ...  126157.831500  126157.83150  126157.831500
48   27580.16775  ...   66653.210610   75533.94662   90101.314670
49   11136.16775  ...  111110.042100  119990.77810  134558.146200
50  312800.16780  ...  400299.720400  410233.95520  422178.770600
51 -294919.50950  ... -442929.563100 -451401.41200 -453463.978900

           20-May         20-Jun         20-Jul         20-Aug       20-Sep  \
0             NaN            NaN            NaN            NaN          NaN
1             NaN            NaN            NaN            NaN          NaN
2  -178977.277000 -188409.123900 -195917.586700 -201727.641700 -206473.3864
3             NaN            NaN            NaN            NaN          NaN
4     7125.000000    7125.000000    7125.000000    7125.000000    7125.0000
5             NaN            NaN            NaN            NaN          NaN
6  -171852.277000 -181284.123900 -188792.586700 -194602.641700 -199348.3864
7        0.000000       0.000000       0.000000       0.000000       0.0000
8        0.000000       0.000000       0.000000       0.000000       0.0000
9        0.000000       0.000000       0.000000       0.000000       0.0000
10       0.000000       0.000000       0.000000       0.000000       0.0000
11 -171852.277000 -181284.123900 -188792.586700 -194602.641700 -199348.3864
12            NaN            NaN            NaN            NaN          NaN
13    8251.928267    4875.818637    9192.334033    5296.619341   10302.1187
14  282640.000000  282020.000000  281400.000000  280780.000000  280160.0000
15            NaN            NaN            NaN            NaN          NaN
16  290891.928300  286895.818600  290592.334000  286076.619300  290462.1187
17            NaN            NaN            NaN            NaN          NaN
18  290891.928300  286895.818600  290592.334000  286076.619300  290462.1187
19   18299.000000   18299.000000   18299.000000   18299.000000   18299.0000
20 -100000.000000 -100000.000000 -100000.000000 -100000.000000 -100000.0000
21  126157.831500  126157.831500  126157.831500  126157.831500  126157.8315
22   98346.434210  106101.699500  108237.126200  129153.695000  140196.0800
23  142803.265700  150558.531000  152693.957700  173610.526500  184652.9115
24  433695.194000  437454.349600  443286.291700  459687.145800  475115.0302
25 -462744.205200 -468179.942600 -479384.920800 -480679.261100 -489810.5051
26            NaN            NaN            NaN            NaN          NaN
27            NaN            NaN            NaN            NaN          NaN
28 -178977.277000 -188409.123900 -195917.586700 -201727.641700 -206473.3864
29            NaN            NaN            NaN            NaN          NaN
30    7125.000000    7125.000000    7125.000000    7125.000000    7125.0000
31            NaN            NaN            NaN            NaN          NaN
32 -171852.277000 -181284.123900 -188792.586700 -194602.641700 -199348.3864
33       0.000000       0.000000       0.000000       0.000000       0.0000
34       0.000000       0.000000       0.000000       0.000000       0.0000
35       0.000000       0.000000       0.000000       0.000000       0.0000
36       0.000000       0.000000       0.000000       0.000000       0.0000
37 -171852.277000 -181284.123900 -188792.586700 -194602.641700 -199348.3864
38            NaN            NaN            NaN            NaN          NaN
39    8251.928267    4875.818637    9192.334033    5296.619341   10302.1187
40  282640.000000  282020.000000  281400.000000  280780.000000  280160.0000
41            NaN            NaN            NaN            NaN          NaN
42  290891.928300  286895.818600  290592.334000  286076.619300  290462.1187
43            NaN            NaN            NaN            NaN          NaN
44  290891.928300  286895.818600  290592.334000  286076.619300  290462.1187
45   18299.000000   18299.000000   18299.000000   18299.000000   18299.0000
46 -100000.000000 -100000.000000 -100000.000000 -100000.000000 -100000.0000
47  126157.831500  126157.831500  126157.831500  126157.831500  126157.8315
48   98346.434210  106101.699500  108237.126200  129153.695000  140196.0800
49  142803.265700  150558.531000  152693.957700  173610.526500  184652.9115
50  433695.194000  437454.349600  443286.291700  459687.145800  475115.0302
51 -462744.205200 -468179.942600 -479384.920800 -480679.261100 -489810.5051

           20-Oct       20-Nov
0             NaN          NaN
1             NaN          NaN
2  -214408.974400 -211607.3621
3             NaN          NaN
4     7125.000000    7125.0000
5             NaN          NaN
6  -207283.974400 -204482.3621
7        0.000000       0.0000
8        0.000000       0.0000
9        0.000000       0.0000
10       0.000000       0.0000
11 -207283.974400 -204482.3621
12            NaN          NaN
13    4990.502267   13036.0000
14  279540.000000  278920.0000
15            NaN          NaN
16  284530.502300  291956.0000
17            NaN          NaN
18  284530.502300  291956.0000
19   18299.000000   18299.0000
20 -100000.000000 -100000.0000
21  126157.831500  126157.8315
22  159845.231300  191654.0940
23  204302.062800  236110.9255
24  488832.565000  528066.9255
25 -491814.476700 -496438.3621
26            NaN          NaN
27            NaN          NaN
28 -214408.974400 -211607.3621
29            NaN          NaN
30    7125.000000    7125.0000
31            NaN          NaN
32 -207283.974400 -204482.3621
33       0.000000       0.0000
34       0.000000       0.0000
35       0.000000       0.0000
36       0.000000       0.0000
37 -207283.974400 -204482.3621
38            NaN          NaN
39    4990.502267   13036.0000
40  279540.000000  278920.0000
41            NaN          NaN
42  284530.502300  291956.0000
43            NaN          NaN
44  284530.502300  291956.0000
45   18299.000000   18299.0000
46 -100000.000000 -100000.0000
47  126157.831500  126157.8315
48  159845.231300  191654.0940
49  204302.062800  236110.9255
50  488832.565000  528066.9255
51 -491814.476700 -496438.3621

[52 rows x 37 columns]

In [103]:
#np.shape(BS_df)
#type(BS_df)
BS_array = np.array(BS_df)[:, 1:]
#BS_assets_key_lines = BS_array[asset_key_lines]
rows, cols = np.shape(BS_array)
BS_array_prev = np.c_[np.zeros((rows, 1)), BS_array[:, 0:cols-1]]

#np.shape(BS_array[:, 0:cols-1])
#np.shape(np.zeros((rows, 1)))
#np.shape(BS_array[0: cols-1])

BS_movement = (BS_array - BS_array_prev)[:,1:]
#print(BS_movement)

BS_reshape_movement = np.reshape(BS_movement, (rows// number_companies, number_months-1, number_companies))
print(BS_reshape_movement)

[[[nan nan]
  [nan nan]
  [nan nan]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 [[-7661.352070000001 -888.3921000000009]
  [-894.4091499999995 -3582.8152900000023]
  [-1728.950929999999 -9036.03935]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 [[-4750.0 0.0]
  [-4750.0 0.0]
  [-2375.0 0.0]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 ...

 [[0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  ...
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[-5641.178250000001 5399.483250000001]
  [-1646.1052500000005 4780.5562500000015]
  [-2034.7822500000002 803.1292499999981]
  ...
  [7755.265299999999 2135.426700000011]
  [20916.56880000001 11042.38499999998]
  [19649.151300000027 31808.862699999998]]

 [[-8122.952099999995 4037.257100000046]
  [-369.10530000005383 1890.5563000000548]
  [1756.2176999999792 -3643.8707000000286]
  ...
  [-5435.737399999984 -11204.978200000012]
  [-1294.3402999999817 -9131.244000000006]
  [-2003.9715999999898 -4623.885400000028]]]

In [104]:
BS_assets = ["Assets",
"Short-term Assets",
"Cash",
"Accounts Receivable",
"Inventory",
"Other Short-term Assets",
"Total Short-term Assets",
"Long-term Assets",
"Capital Assets",
"Accumulated Depreciation",
"Total Long-term Assets",
"Total Assets"
]


Assets_key_lines = [
"Accounts Receivable",
"Inventory",
"Other Short-term Assets",
"Long-term Assets",
]




type(BS_assets)

list

In [105]:
BS_liabilities = [
"Liabilities and Capital",
"Accounts Payable",
"Short-term Notes",
"Other Short-term Liabilities",
"Subtotal Short-term Liabilities",
"Long-term Liabilities",
"Total Liabilities",
"Paid in Capital",
"Dividends paid",
"Retained Earnings",
"Earnings",
"Total Capital",
"Total Liabilities and Capital",
"Net Worth"
]

Liabilities_key_lines = [
"Accounts Payable",
"Short-term Notes",
"Other Short-term Liabilities",
"Long-term Liabilities",
]



print(BS_liabilities)

['Liabilities and Capital', 'Accounts Payable', 'Short-term Notes', 'Other Short-term Liabilities', 'Subtotal Short-term Liabilities', 'Long-term Liabilities', 'Total Liabilities', 'Paid in Capital', 'Dividends paid', 'Retained Earnings', 'Earnings', 'Total Capital', 'Total Liabilities and Capital', 'Net Worth']

In [107]:
BS_array = np.array(BS_df)
BS_assets_key_lines = BS_array[np.isin(BS_array[:,0], Assets_key_lines)][:, 1:]

rows, cols = np.shape(BS_assets_key_lines)
BS_assets_key_lines_prev = np.c_[np.zeros((rows, 1)), BS_assets_key_lines[:, 0:cols-1]]

#np.shape(BS_array[:, 0:cols-1])
#np.shape(np.zeros((rows, 1)))
#np.shape(BS_array[0: cols-1])

BS_assets_movement = (BS_assets_key_lines - BS_assets_key_lines_prev)[:,1:]
#print(BS_assets_movement)


BS_reshape_assets_movement = np.moveaxis(np.reshape(BS_assets_movement, (  number_companies, number_months-1, rows//number_companies)), [0, 2], [2, 0])

#print(BS_assets_key_lines)

BS_positive_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement >= 0]
BS_negative_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement < 0]
#print(BS_positive_assets_movement)
#print(BS_negative_assets_movement)

#np.moveaxis(BS_reshape_assets_movement, [0, 1, 2], [2, 0, 1]).shape
#np.shape(BS_reshape_assets_movement)
print(BS_reshape_assets_movement)

[[[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-4750.0 -4750.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-4750.0 -4750.0]
  [-2375.0 -2375.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]]

<ipython-input-107-985e3cf2154d>:19: RuntimeWarning: invalid value encountered in greater_equal
  BS_positive_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement >= 0]
<ipython-input-107-985e3cf2154d>:20: RuntimeWarning: invalid value encountered in less
  BS_negative_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement < 0]

In [112]:
BS_array = np.array(BS_df)
BS_liabilities_key_lines = BS_array[np.isin(BS_array[:,0], Liabilities_key_lines)][:, 1:]

rows, cols = np.shape(BS_liabilities_key_lines)
BS_liabilities_key_lines_prev = np.c_[np.zeros((rows, 1)), BS_liabilities_key_lines[:, 0:cols-1]]

#np.shape(BS_array[:, 0:cols-1])
#np.shape(np.zeros((rows, 1)))
#np.shape(BS_array[0: cols-1])

BS_liabilities_movement = (BS_liabilities_key_lines - BS_liabilities_key_lines_prev)[:,1:]
#print(BS_assets_movement)


BS_reshape_liabilities_movement = np.moveaxis(np.reshape(BS_liabilities_movement, (  number_companies, number_months-1, rows//number_companies)), [0, 2], [2, 0])
print(BS_reshape_liabilities_movement[:,0,0])
#print(BS_assets_key_lines)

BS_positive_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement >= 0]
BS_negative_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement < 0]
print(BS_positive_liabilities_movement)
print(BS_negative_liabilities_movement)

[-2482.0 -742.0 1897.0 -2270.0]
[[[[0.0 0.0]
   [4411.0 4411.0]
   [5674.0 5674.0]
   [0.0 0.0]
   [3179.6692160000007 3179.6692160000007]
   [4090.1027270000004 4090.1027270000004]
   [0.0 0.0]
   [3891.3037829999994 3891.3037829999994]
   [5005.499359000001 5005.499359000001]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[1897.0 1897.0]
   [4893.0 4893.0]
   [9120.0 9120.0]
   [1367.4523919999997 1367.4523919999997]
   [3527.1189009999994 3527.1189009999994]
   [6574.1517220000005 6574.1517220000005]
   [1673.4988159999994 1673.4988159999994]
   [4316.515396 4316.515396]
   [8045.497733 8045.497733]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]]]
[[[[2482.0 2482.0]
   [0.0 0.0]
   [0.0 0.0]
   [1789.1496239999997 1789.1496239999997]
   [0.0 0.0]
   [0.0 0.0]
   [2189.575150999999 2189.575150999999]
   [0.0 0.0]
   [0.0 0.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[742.0 742.0]
   [3827.0 3827.0]
   [6021.0 6021.0]
   [534.8706779999998 534.8706779999998]
   [2758.6928330000005 2758.6928330000005]
   [4340.237666000001 4340.237666000001]
   [654.578872 654.578872]
   [3376.10963 3376.10963]
   [5311.616433000001 5311.616433000001]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[2270.0 2270.0]
   [4416.0 4416.0]
   [8620.94126 8620.94126]
   [1636.3294309999997 1636.3294309999997]
   [3183.2734659999996 3183.2734659999996]
   [3118.1676930000003 3118.1676930000003]
   [2002.552616 2002.552616]
   [3895.7146919999996 3895.7146919999996]
   [0.0 0.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [620.0 620.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]]]

<ipython-input-112-a2fe70d709a4>:19: RuntimeWarning: invalid value encountered in greater_equal
  BS_positive_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement >= 0]
<ipython-input-112-a2fe70d709a4>:20: RuntimeWarning: invalid value encountered in less
  BS_negative_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement < 0]

In [108]:
Cashflow_lines = [
"Net Profit",
"Plus:",
"Depreciation",
"Change in Accounts Payable",
"Current Borrowing (repayment)",
"Increase (decrease) Other Liabilities",
"Long-term Borrowing (repayment)",
"Capital Input",
"Subtotal",
"Less:",
"Change in Accounts Receivable",
"Change in Inventory",
"Change in Other Short-term Assets",
"Capital Expenditure",
"Dividends",
"Subtotal",
"Net Cash Flow",
"Cash Balance",
]

type(Cashflow_lines)

list

In [109]:
Cashflow_lines = [
"Net Profit",
"Plus:",
"Depreciation",
"Change in Accounts Payable",
"Current Borrowing (repayment)",
"Increase (decrease) Other Liabilities",
"Long-term Borrowing (repayment)",
"Capital Input",
"Subtotal",
"Less:",
"Change in Accounts Receivable",
"Change in Inventory",
"Change in Other Short-term Assets",
"Capital Expenditure",
"Dividends",
"Subtotal",
"Net Cash Flow",
"Cash Balance",
]

standard_cashflow_lines =[
"Operating cash flow",
"Net earnings",
"Plus: depreciation and amortisation",
"Less:  changes in Working capital",
"Cash from operations",
"Investing cashflow",
"Investments in property & equipment",
"Cash from investing",
"Financing cashflow",
"Issuance (repayment) of debt",
"Issuance (repayment) of equity",
"Cash from Financing",
"Net increase (decrease) in cash",
"Opening cash",
"Closing cash"
]

standard_cashflow_lines_mapping ={
"Net Profit" : ["Net earnings", "plus"],
"Plus:" : ["text", "text"],
"Depreciation" : ["plus: depreciation and amortisation", "plus"],
"Change in Accounts Payable" : ["Less: changes in Working capital", "less"],
"Current Borrowing (repayment)" : ["Issuance (repayment) of debt", "plus"],
"Increase (decrease) Other Liabilities" : ["Less: changes in Working capital", "less"],
"Long-term Borrowing (repayment)" : ["Issuance (repayment) of debt", "plus"],
"Capital Input" : ["Issuance (repayment) of equity", "plus"],
"Subtotal" : ["text", "text"],
"Less:" : ["text", "text"],
"Change in Accounts Receivable" : ["Less:  changes in Working capital", "less"],
"Change in Inventory" : ["Less:  changes in Working capital", "less"],    
"Change in Other Short-term Assets" : ["Less:  changes in Working capital", "less"],
"Capital Expenditure" : ["Investments in property & equipment", "less"],
"Dividends" : ["Issuance (repayment) of equity", "plus"],
"Net Cash Flow" : ["rec", "sum"],
"Cash Balance" : ["Closing cash", "rec"]
}

In [110]:
to = 0
sign = 1

print(standard_cashflow_lines_mapping["Net Profit"][to])
print(standard_cashflow_lines_mapping["Net Profit"][sign])
#print(Cashflow_lines)

Net earnings
plus

In [121]:
#print(BS_array)

BS_assets_standard_lines = BS_array[np.isin(BS_array[:,0], standard_cashflow_lines_mapping.keys)][:, 1:]

print(BS_assets_standard_lines)

[]

In [430]:
Pnl_and_BS_adj_array = np.concatenate((PATValue[1:,:], DepreciationValue[1:,:]), axis= 0)
nrows, ncols = np.shape(Pnl_and_BS_adj_array)
Pnl_and_BS_adj_reshape_array = np.reshape(Pnl_and_BS_adj_array, (nrows// (number_months-1) , number_months-1, number_companies))

Paidin_cap_reshape_array = np.reshape(PaidInCapitalValue[1:,:], (1 , number_months-1, number_companies))

Div_and_Cash_array = np.concatenate((PaidInCapitalValue[1:,:], DepreciationValue[1:,:]), axis= 0)
nrows, ncols = np.shape(Div_and_Cash_array)
Div_and_Cash_reshape_array = np.reshape(Div_and_Cash_array, (nrows// (number_months-1) , number_months-1, number_companies))

#print (Div_and_Cash_reshape_array)
#np.shape(Div_and_Cash_reshape_array)
#np.shape(BS_reshape_assets_movement)

In [432]:
#np.shape(Pnl_and_BS_adj_array)
np.shape(BS_reshape_assets_movement)

(4, 35, 2)

In [433]:
cashflow_array = np.concatenate((Pnl_and_BS_adj_reshape_array,
                                -1 * (BS_reshape_assets_movement),
                                Paidin_cap_reshape_array,
                                BS_reshape_liabilities_movement,
                                Div_and_Cash_reshape_array                                 
                                ), axis = 0)


np.shape(cashflow_array)
print(cashflow_array)

[[[-9929.352071 -9929.352071]
  [473.6079057 473.6079057]
  [-6921.409154000001 -6921.409154000001]
  [-692.815291 -692.815291]
  [-7894.950923 -7894.950923]
  [-4589.039350999999 -4589.039350999999]
  [-10396.54553 -10396.54553]
  [298.531136 298.531136]
  [-7810.632797 -7810.632797]
  [-633.5234582 -633.5234582]
  [-2143.6559850000003 -2143.6559850000003]
  [16094.132480000002 16094.132480000002]
  [-10124.816429999999 -10124.816429999999]
  [72.88637183 72.88637183]
  [-7284.038479999999 -7284.038479999999]
  [-1012.977667 -1012.977667]
  [-8191.7618760000005 -8191.7618760000005]
  [-4786.269061999999 -4786.269061999999]
  [-10611.781790000001 -10611.781790000001]
  [-47.0708586 -47.0708586]
  [-8146.245784000001 -8146.245784000001]
  [-926.8495602 -926.8495602]
  [-2751.8127 -2751.8127]
  [12301.80926 12301.80926]
  [-10883.41833 -10883.41833]
  [-1124.026954 -1124.026954]
  [-8471.848918000002 -8471.848918000002]
  [-2062.566803 -2062.566803]
  [-9280.226391 -9280.226391]
  [-5435.7373210000005 -5435.7373210000005]
  [-11204.97819 -11204.97819]
  [-1294.340311 -1294.340311]
  [-9131.244001000001 -9131.244001000001]
  [-2003.971591 -2003.971591]
  [-4623.885446 -4623.885446]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [4750.0 4750.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [4750.0 4750.0]
  [2375.0 2375.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]
  [-0.0 -0.0]]

 [[18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]]

 [[-2482.0 -2482.0]
  [4411.0 4411.0]
  [5674.0 5674.0]
  [-1789.1496239999997 -1789.1496239999997]
  [3179.6692160000007 3179.6692160000007]
  [4090.1027270000004 4090.1027270000004]
  [-2189.575150999999 -2189.575150999999]
  [3891.3037829999994 3891.3037829999994]
  [5005.499359000001 5005.499359000001]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[-742.0 -742.0]
  [-3827.0 -3827.0]
  [-6021.0 -6021.0]
  [-534.8706779999998 -534.8706779999998]
  [-2758.6928330000005 -2758.6928330000005]
  [-4340.237666000001 -4340.237666000001]
  [-654.578872 -654.578872]
  [-3376.10963 -3376.10963]
  [-5311.616433000001 -5311.616433000001]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[1897.0 1897.0]
  [4893.0 4893.0]
  [9120.0 9120.0]
  [1367.4523919999997 1367.4523919999997]
  [3527.1189009999994 3527.1189009999994]
  [6574.1517220000005 6574.1517220000005]
  [1673.4988159999994 1673.4988159999994]
  [4316.515396 4316.515396]
  [8045.497733 8045.497733]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[-2270.0 -2270.0]
  [-4416.0 -4416.0]
  [-8620.94126 -8620.94126]
  [-1636.3294309999997 -1636.3294309999997]
  [-3183.2734659999996 -3183.2734659999996]
  [-3118.1676930000003 -3118.1676930000003]
  [-2002.552616 -2002.552616]
  [-3895.7146919999996 -3895.7146919999996]
  [0.0 0.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [-620.0 -620.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]]

 [[18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]
  [18299 18299]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]

In [434]:
np.shape(BS_reshape_assets_movement)

(4, 35, 2)

In [438]:
header = [ 
"party_id",
"month",
"Net Profit",
"Depreciation",
"Change in Accounts Payable",
"Decrease in Current Borrowing (repayment)",
"Increase (decrease) Other Liabilities",
"Decrease in Long-term Borrowing (repayment)",
"Capital Input",
"Change in Accounts Receivable",
"Change in Inventory",
"Change in Other Short-term Assets",
"Change in LT/ Capital Assets",
"Dividends",
"Cash Balance"
]

header_cashflow = np.reshape(header, (1, len(header)))

In [440]:
cashflow_months = months[1:]
cashflow_out = np.reshape(cashflow_array, (len(cashflow_months) * number_companies, len(header)-2))
np.shape(cashflow_out)

(70, 13)

In [441]:


number_cashflow_months = len(cashflow_months)
party_id =  np.reshape(([np.ones(number_cashflow_months) * company for company in range(number_companies)]),  (number_companies * number_cashflow_months, 1) )
#np.shape(party_id)
cashflow_months_out = np.reshape(cashflow_months*number_companies, (len(cashflow_months*number_companies), 1))
np.shape(cashflow_months_out)
#np.shape(cashflow_out)

(70, 1)

In [442]:
block_cashflow = np.concatenate((party_id, cashflow_months_out, cashflow_out), axis = 1)
#block_cashflow_out = np.concatenate((header, block_cashflow), axis = 1)

In [443]:
#np.shape(block_cashflow)
block_cashflow_out = np.concatenate((header_cashflow, block_cashflow), axis = 0)

In [444]:
pd.DataFrame(block_cashflow_out).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\cashflowv2.csv", header=None, index=None)

In [499]:
pd.DataFrame(block_cashflow_out).to_sql('cashflowv2', conn, if_exists='replace', index = False)

In [445]:
# nba customer embedding

ESG_risk = np.reshape([0] * number_companies, (1, number_companies))
#past_repayment_history = np.reshape([0] * number_companies, (1, number_companies))
#lodgements_in_bank_account_in_last_3months = np.reshape([0] * number_companies, (1, number_companies))
EBITDA = np.reshape([0] * number_companies, (1, number_companies))
adjusted_EBITDA = np.reshape([0] * number_companies, (1, number_companies)) #(captial withdrawals added back in) 
funding_gap = np.reshape([0] * number_companies, (1, number_companies)) # of business 
#IsUsing_all_facilities_already_paid_for = np.reshape([0] * number_companies, (1, number_companies)) #e.g. overdraft (intra day)
#age_of_account = np.reshape([0] * number_companies, (1, number_companies))
overseas_invoices_ge_50k = np.reshape([0] * number_companies, (1, number_companies))
DigitalRetailerNegCCC = np.reshape([0] * number_companies, (1, number_companies))
UnencumberedAsset = np.reshape([0] * number_companies, (1, number_companies))
InvoiceOpportunity = np.reshape([0] * number_companies, (1, number_companies))
AssetNearEndOfLife = np.reshape([0] * number_companies, (1, number_companies))

In [487]:
#type(datetime.datetime.now())
#type(commercial_df['date of incorporation'])
#type(commercial_df['date of incorporation'].dt)
#type(pd.to_datetime(commercial_df['date of incorporation']).dt)
#print(pd.to_datetime(commercial_df['date of incorporation']))

#t = ((datetime.datetime.now() - pd.to_datetime(commercial_df['date of incorporation']))/ np.timedelta64(1, 'D')).astype(int)
#print(t/30)

In [488]:
import datetime

age_of_account = np.array(((datetime.datetime.now() - pd.to_datetime(commercial_df['date of incorporation']))/ np.timedelta64(1, 'D')).astype(int)) /30
#print(age_of_account)
age_of_account_reshape = np.reshape(age_of_account, (1, number_companies))
#age_of_account_reshape.shape

In [489]:
past_repayment_history = np.array(OpenBanking_df['lending in arrears'])
past_repayment_history_reshape = np.reshape(past_repayment_history, (1, number_companies))
lodgements_in_bank_account_in_last_3months = np.array(OpenBanking_df['lodgement in last 3 months'])
lodgements_in_bank_account_in_last_3months_reshape = np.reshape(lodgements_in_bank_account_in_last_3months, (1, number_companies))
#past_repayment_history.shape
#print(past_repayment_history)

In [490]:
IsUsing_all_facilities_already_paid_for = (np.array(OpenBanking_df['overdraft limit']) + np.array(OpenBanking_df['current account balance'])) >0
IsUsing_all_facilities_already_paid_for_reshape = np.reshape(IsUsing_all_facilities_already_paid_for, (1, number_companies))

In [491]:
customer_embedding_array = np.concatenate((risk_profile,
                                           ESG_risk,
                                           past_repayment_history_reshape,
                                           lodgements_in_bank_account_in_last_3months_reshape,
                                           EBITDA,
                                           adjusted_EBITDA,
                                           funding_gap,
                                           IsUsing_all_facilities_already_paid_for_reshape,
                                           age_of_account_reshape,
                                           overseas_invoices_ge_50k,
                                           DigitalRetailerNegCCC,
                                           UnencumberedAsset,
                                           InvoiceOpportunity,
                                           AssetNearEndOfLife                              
                                          ), axis = 0)

In [492]:
#score = np.matmul(NBA_scorecard_array, customer_embedding_array )
#np.shape(score)
NBA_scorecard_array=np.array(NBA_scorecard_df)[2:,2:]

#type(customer_embedding_array)
score = np.matmul(NBA_scorecard_array.astype(float), customer_embedding_array.astype(float) )
np.shape(score)
print(score)

number_actions = np.shape(score)[0]
order = np.argsort(-score, axis=0)
print(number_actions)

[[ 0.00000000e+00  0.00000000e+00]
 [-9.99000000e+02 -9.99000000e+02]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.00000000e+00  5.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.00000000e+01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.20000000e+01  1.00000000e+00]
 [ 1.38133333e+03  2.64666667e+02]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]]
18

In [493]:
header = [ 
"Id",
"PartyId",
"QueueType",
"Fit Score",
"DateCreated",
"Status",
"DateClosed"
]

header_nba = np.reshape(header, (1, len(header)))

print(header_nba)

[['Id' 'PartyId' 'QueueType' 'Fit Score' 'DateCreated' 'Status'
  'DateClosed']]

In [494]:
block = np.reshape(header, (1, len(header)))
count_all_nba = 0
for company in range(number_companies) :
    id = []
    party_id = []
    QueueType=[]
    Fit_score =[]
    DateCreated = []
    Status = []
    DateClosed = []
    count_nba = 0
    for action in range(number_actions) :
       if score[action, company] > 0 :
          id = np.append(id, count_all_nba)
          party_id = np.append(party_id, str(company))
          QueueType = np.append(QueueType, actions_df.loc[action][1])  
          Fit_score= np.append(Fit_score, score[action, company])
          DateCreated = np.append(DateCreated,["8/31/2020  12:00:00 AM"]) 
          Status = np.append(Status, ["Open"])
          DateClosed = np.append(DateClosed,[""])   
          count_nba += 1  
          count_all_nba += 1
       next_block = np.concatenate((id, party_id, QueueType, Fit_score, DateCreated, Status, DateClosed), axis = 0)  
       cols = count_nba
       rows = len(header)
       next_block_reshape = np.reshape(next_block, (rows, cols))    
       next_block_reshape_transpose = next_block_reshape.T
    block = np.concatenate((block, next_block_reshape_transpose), axis=0)

print(block)

[['Id' 'PartyId' 'QueueType' 'Fit Score' 'DateCreated' 'Status'
  'DateClosed']
 ['0.0' '0'
  'Conduct - improve efficiency of current finance facilities - use of fx facility (rates) - criteria check : fx margin observed vs offered rate'
  '5.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['1.0' '0'
  'Liquidity - support business owners growth objectives - support expanded sales growth through cashflow support e.g export credit lines, invoice finance - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and overseas invoices'
  '50.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['2.0' '0'
  'Contagion - sustain and protect business - interest rate and fx hedge products - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and  interest rate volitility / earnings or fx volitility / earnings> threshold.  Large earnings residual risk due to rigid mis alignment of contract terms between supply vs demand markets'
  '12.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['3.0' '0'
  'Trade - sustain and protect business - assets approaching end of amortised life/renew production/ operational assets - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and depreciation curve of assets nears end or has ended & asset class with high tech/ efficiency progress'
  '1381.3333333333333' '8/31/2020  12:00:00 AM' 'Open' '']
 ['4.0' '1'
  'Conduct - improve efficiency of current finance facilities - use of fx facility (rates) - criteria check : fx margin observed vs offered rate'
  '5.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['5.0' '1'
  'Contagion - sustain and protect business - interest rate and fx hedge products - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and  interest rate volitility / earnings or fx volitility / earnings> threshold.  Large earnings residual risk due to rigid mis alignment of contract terms between supply vs demand markets'
  '1.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['6.0' '1'
  'Trade - sustain and protect business - assets approaching end of amortised life/renew production/ operational assets - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and depreciation curve of assets nears end or has ended & asset class with high tech/ efficiency progress'
  '264.66666666666663' '8/31/2020  12:00:00 AM' 'Open' '']]

In [495]:
print(actions_df.loc[1][1])

Fraud - Investigate - due diligence to establish legitimacy and authenticity of business

In [496]:
pd.DataFrame(block).to_csv(r"\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\NextBestActionv2.csv", header=None, index=None)

In [498]:
pd.DataFrame(block).to_sql('NextBestActionv2', conn, if_exists='replace', index = False)